# Ansible Collections for AWX Project
collections:
  - name: community.general
    version: ">=7.0.0"
  - name: ansible.posix  
    version: ">=1.5.0"
  - name: community.crypto
    version: ">=2.0.0"
  - name: community.network
    version: ">=5.0.0"
  - name: dellemc.openmanage
    version: ">=7.0.0"
  - name: hpe.oneview
    version: ">=6.0.0"
  - name: community.vmware
    version: ">=3.0.0"
