---
# vSphere VM 관리 핸들러

- name: restart vm
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    port: "{{ vcenter_port }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    name: "{{ vm_name }}"
    datacenter: "{{ datacenter }}"
    state: reboot-guest
    state_change_timeout: "{{ power_off_timeout + power_on_timeout }}"
  delegate_to: localhost

- name: power off vm
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    port: "{{ vcenter_port }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    name: "{{ vm_name }}"
    datacenter: "{{ datacenter }}"
    state: powered-off
    state_change_timeout: "{{ power_off_timeout }}"
  delegate_to: localhost

- name: power on vm
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    port: "{{ vcenter_port }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    name: "{{ vm_name }}"
    datacenter: "{{ datacenter }}"
    state: powered-on
    state_change_timeout: "{{ power_on_timeout }}"
  delegate_to: localhost

- name: unmount iso
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    port: "{{ vcenter_port }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ datacenter }}"
    name: "{{ vm_name }}"
    state: present
    cdrom:
      - controller_type: "{{ cdrom_controller_type }}"
        controller_number: "{{ cdrom_controller_number }}"
        unit_number: "{{ cdrom_unit_number }}"
        state: absent
  delegate_to: localhost