---
- name: Supermicro 펌웨어 업그레이드 시작
  debug:
    msg: "Supermicro 서버 펌웨어 업그레이드를 시작합니다"

- name: Supermicro Update Manager 확인
  command: which sum
  register: sum_installed
  ignore_errors: yes
  changed_when: false

- name: Supermicro Update Manager 설치
  block:
    - name: SUM 다운로드
      get_url:
        url: "{{ firmware_repo_url }}/supermicro/sum/sum_2.11.0_Linux_x86_64.tar.gz"
        dest: "{{ firmware_local_path }}/sum.tar.gz"

    - name: SUM 압축 해제
      unarchive:
        src: "{{ firmware_local_path }}/sum.tar.gz"
        dest: "{{ firmware_local_path }}"
        remote_src: yes

    - name: SUM 실행 권한 부여
      file:
        path: "{{ firmware_local_path }}/sum"
        mode: '0755'

  when: sum_installed.rc != 0

- name: BMC 정보 확인
  command: "{{ firmware_local_path }}/sum -i {{ ansible_default_ipv4.address }} -u {{ ipmi_user }} -p {{ ipmi_password }} --check_before_update"
  register: supermicro_bmc_info
  ignore_errors: yes

- name: 현재 펌웨어 버전 확인
  command: "{{ firmware_local_path }}/sum -i {{ ansible_default_ipv4.address }} -u {{ ipmi_user }} -p {{ ipmi_password }} --get_fw_info"
  register: current_fw_info
  ignore_errors: yes

- name: BIOS 펌웨어 업그레이드
  block:
    - name: BIOS 펌웨어 파일 다운로드
      get_url:
        url: "{{ firmware_repo_url }}/supermicro/bios/{{ ansible_product_name | replace(' ', '_') }}/BIOS.bin"
        dest: "{{ firmware_local_path }}/BIOS.bin"

    - name: BIOS 업그레이드 실행
      command: "{{ firmware_local_path }}/sum -i {{ ansible_default_ipv4.address }} -u {{ ipmi_user }} -p {{ ipmi_password }} --file {{ firmware_local_path }}/BIOS.bin --update_type bios"
      register: bios_upgrade_result
      async: 1800
      poll: 30

- name: BMC 펌웨어 업그레이드
  block:
    - name: BMC 펌웨어 파일 다운로드
      get_url:
        url: "{{ firmware_repo_url }}/supermicro/bmc/{{ ansible_product_name | replace(' ', '_') }}/BMC.bin"
        dest: "{{ firmware_local_path }}/BMC.bin"

    - name: BMC 업그레이드 실행
      command: "{{ firmware_local_path }}/sum -i {{ ansible_default_ipv4.address }} -u {{ ipmi_user }} -p {{ ipmi_password }} --file {{ firmware_local_path }}/BMC.bin --update_type bmc"
      register: bmc_upgrade_result
      async: 1200
      poll: 30

    - name: BMC 재시작 대기
      wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: 443
        timeout: 600
        delay: 120

- name: 업그레이드 상태 확인
  command: "{{ firmware_local_path }}/sum -i {{ ansible_default_ipv4.address }} -u {{ ipmi_user }} -p {{ ipmi_password }} --get_fw_info"
  register: updated_fw_info
  retries: 5
  delay: 60

- name: 업그레이드 결과 비교
  debug:
    msg: |
      업그레이드 전: {{ current_fw_info.stdout }}
      업그레이드 후: {{ updated_fw_info.stdout }}

- name: 시스템 재부팅 (필요시)
  reboot:
    reboot_timeout: "{{ upgrade_timeout }}"
  when: reboot_after_upgrade and bios_upgrade_result.changed

- name: Supermicro 펌웨어 업그레이드 완료
  debug:
    msg: "Supermicro 서버 펌웨어 업그레이드가 완료되었습니다"
