---
# 베어메탈 서버 완전 설정 플레이북
# OS 설치, 펌웨어 업그레이드, 드라이버 설치를 순차적으로 실행

- name: 베어메탈 서버 완전 설정
  hosts: baremetal_servers
  become: yes
  serial: 1  # 한 번에 하나씩 처리하여 안전성 확보
  gather_facts: yes
  
  vars:
    setup_stage: "{{ stage | default('all') }}"  # all, os_only, firmware_only, driver_only
    
  pre_tasks:
    - name: 서버 상태 확인
      ping:
      
    - name: 시작 시간 기록
      set_fact:
        job_start_time: "{{ ansible_date_time.epoch }}"
        
    - name: 작업 로그 디렉토리 생성
      file:
        path: "/var/log/baremetal-setup"
        state: directory
        mode: '0755'

  tasks:
    # OS 설치 단계
    - name: OS 설치 실행
      include_role:
        name: os_install
      when: setup_stage in ['all', 'os_only']
      tags: 
        - os_install
        - never  # 명시적으로 지정할 때만 실행

    # 펌웨어 업그레이드 단계  
    - name: 펌웨어 업그레이드 실행
      include_role:
        name: firmware_upgrade
      when: setup_stage in ['all', 'firmware_only']
      tags: 
        - firmware_upgrade

    # 드라이버 설치 단계
    - name: 드라이버 설치 실행
      include_role:
        name: driver_install
      when: setup_stage in ['all', 'driver_only']
      tags: 
        - driver_install

  post_tasks:
    - name: 완료 시간 기록
      set_fact:
        job_end_time: "{{ ansible_date_time.epoch }}"
        
    - name: 작업 소요 시간 계산
      set_fact:
        job_duration: "{{ ((job_end_time | int) - (job_start_time | int)) | int }}"
        
    - name: 최종 상태 확인
      setup:
      
    - name: 작업 완료 로그 작성
      lineinfile:
        path: "/var/log/baremetal-setup/setup-{{ ansible_hostname }}-{{ ansible_date_time.date }}.log"
        line: "{{ ansible_date_time.iso8601 }} - 베어메탈 설정 완료 (소요시간: {{ job_duration }}초)"
        create: yes

  handlers:
    - name: 시스템 재부팅
      reboot:
        reboot_timeout: 600
        
    - name: 서비스 재시작 대기
      wait_for_connection:
        timeout: 300
